// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OASv1.Data;

#nullable disable

namespace OASv1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("OASv1.Model.AProductModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeRecebimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeDoProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotaFiscal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsavelPelaBuscaDoProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Validade")
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
